const radcyprawni = [
  {
    name: "Bartosz Nyczek Kancelaria radcy prawnego",
    phone: "(12) 656 50 77",
    site: "http://www.nyczek.pl/pl/kancelaria/",
    email: "kancelaria@nyczek.pl",
  },
  {
    name: "Małgorzata Dróżdż-Stasiak Kancelaria radcy prawnego",
    phone: "660 490 777",
    site: "http://www.radcaprawny-lodz.com",
    email: "malgorzata.stasiak777@gmail.com",
  },
  {
    name: "Kancelaria Prawna Profilegal Skuczyński i Wspólnicy sp.k.",
    phone: "(56) 623 43 82",
    site: "https://www.profilegal.pl/",
    email: "profilegal@profilegal.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Marka Stejblisa",
    phone: "(22) 466 41 43",
    site: "https://arendarski-stejblis.pl/",
    email: "marek.stejblis@arendarski-stejblis.pl",
  },
  {
    name: "Paulina Gugała, Kancelaria Radcy Prawnego",
    phone: "604 064 662",
    site: "https://kancelaria-pg.pl/",
    email: "biuro@kancelaria-pg.pl",
  },
  {
    name: "Radca Prawny Wojciech J. Chmurak",
    phone: "668 361 949",
    site: "https://kancelaria-chmurak.pl/",
    email: "info@kancelaria-chmurak.pl",
  },
  {
    name: "Wojciech J. Chmurak Kancelaria Radcy Prawnego",
    phone: "668 361 949",
    site: "https://kancelaria-chmurak.pl/",
    email: "info@kancelaria-chmurak.pl",
  },
  {
    name: "Tomasz Zawadzki Kancelaria radcy prawnego",
    phone: "600 373 938",
    site: "http://www.kancelaria-zawadzki.eu",
    email: "tz@kancelaria-zawadzki.eu",
  },
  {
    name: "Adwokat Łukasz Lecyk",
    phone: "605 836 220",
    site: "https://adwokat-lecyk.pl/",
    email: "kontakt@adwokat-lecyk.pl",
  },
  {
    name: "Geran Kancelaria Radcy Prawnego Gerard Madejski",
    phone: "602 234 915",
    site: "https://geran.pl/",
    email: "geran@geran.pl",
  },
  {
    name: "Anna Jekiel-Zakrzewska. Kancelaria radcy prawnego",
    phone: "668 396 251",
    site: "http://www.radca-lodz.eu",
    email: "anna.jekiel@gmail.com",
  },
  {
    name: "Równicki Marcin Kancelaria Radcy Prawnego",
    phone: "600 850 054",
    site: "http://www.2k2r.pl",
    email: "kancelaria@marcin-rownicki.pl",
  },
  {
    name: "Izabela Tutro Kancelaria Radcy Prawnego",
    phone: "796 906 306",
    site: "http://www.kancelaria-tutro.pl",
    email: "izabela.tutro@onet.eu",
  },
  {
    name: "Sławomir Momot Kancelaria prawna",
    phone: "662 547 653",
    site: "https://kancelariabialoleka.pl/",
    email: "biuro@kancelariabialoleka.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Dr Małgorzaty Maliszewskiej",
    phone: "(22) 822 30 30",
    site: "http://www.drmaliszewskakancelaria.com",
    email: "prawnik@drmaliszewskakancelaria.com",
  },
  {
    name: "Kancelaria Radcy Prawnego Agata Bilska",
    phone: "505 906 876",
    site: "https://www.kancelariasloneczna.com.pl/",
    email: "agatabilskaa@gmail.com",
  },
  {
    name: "Kancelaria Radcy Rrawnego mgr Krzysztof Baran",
    phone: "(12) 637 03 66",
    site: "http://www.barankancelaria.pl/",
    email: "barankancelaria@pro.onet.pl",
  },
  {
    name: "Błażej Winkler Kancelaria Radcy Prawnego",
    phone: "(61) 853 03 63",
    site: "http://www.winklerkancelaria.pl",
    email: "kancelaria@winklerkancelaria.pl",
  },
  {
    name: "Rafał Grzywacz Kancelaria Radcy Prawnego",
    phone: "(44) 647 50 95",
    site: "http://www.radca-piotrkow.eu",
    email: "rafal.grzywacz@radca-piotrkow.eu",
  },
  {
    name: "Kancelaria Radcy Prawnego Dorota Moros",
    phone: "608 087 934",
    site: "http://www.moros.com.pl",
    email: "moros.prawnik@gmail.com",
  },
  {
    name: "Sołtysiński Kawecki & Szlęzak – Kancelaria Radców Prawnych i Adwokatów Spółka Jawna",
    phone: "(22) 608 70 00",
    site: "https://www.skslegal.pl",
    email: "office@skslegal.pl",
  },
  {
    name: "Bartosz Merda Kancelaria Radcy Prawnego",
    phone: "508 343 810",
    site: "http://kancelaria-merda.pl/",
    email: "kancelaria@radcabm.pl",
  },
  {
    name: "Anna Haak-Trzuskawska Kancelaria Radcy Prawnego",
    phone: "692 691 125",
    site: "http://www.haak-trzuskawska.pl",
    email: "kancelaria.ehaak@op.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Elżbieta Haak",
    phone: "606 416 412",
    site: null,
    email: "kancelaria.ehaak@op.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Aliny Sarackiej",
    phone: "609 673 123",
    site: "https://www.kancelariaalinasaracka.pl",
    email: "mec.alinasaracka@wp.pl",
  },
  {
    name: "Bartosz Merda Kancelaria Radcy Prawnego",
    phone: "508 343 810",
    site: "http://kancelaria-merda.pl/",
    email: "kancelaria@radcabm.pl",
  },
  {
    name: "Cce Kancelaria Radcy Prawnego Radca Prawny Cezary Cieśluk",
    phone: "608 006 003",
    site: "https://www.cezaryciesluk.pl/",
    email: "cezary.ciesluk@gmail.com",
  },
  {
    name: "Sławomir Żur Kancelaria radcy prawnego",
    phone: "608 453 487",
    site: "https://www.radca-wro.com/",
    email: "kancelaria@radca-wro.pl",
  },
  {
    name: "Zdzisław Kliś Kancelaria radcy prawnego",
    phone: "602 246 269",
    site: "http://www.zdzislawklis.pl/",
    email: "kancelaria@zdzislawklis.pl",
  },
  {
    name: "Marcin Bartkowiak Kancelaria radcy prawnego",
    phone: "609 602 633",
    site: "http://krpbartkowiak.pl/",
    email: "kancelaria@krpbartkowiak.pl",
  },
  {
    name: "Piotr Skowron Kancelaria radcy prawnego",
    phone: "600 483 056",
    site: "http://doradcaprawnykatowice.pl/",
    email: "piotrskowron1@poczta.onet.pl",
  },
  {
    name: "Agnieszka Stępień Kancelaria Radcy Prawnego",
    phone: "691 868 894",
    site: "http://stepienkancelaria.pl/",
    email: "kontakt@stepienkancelaria.pl",
  },
  {
    name: "Radca prawny Jóźwiakowska Aneta",
    phone: "602 218 845",
    site: "https://www.radcaprawnyjozwiakowska.pl/",
    email: "anetajozwiakowska@wp.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Piotr Kołodziejczyk",
    phone: "511 470 310",
    site: "http://www.kolodziejczykpiotr.pl",
    email: "kancelaria@kolodziejczykpiotr.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Katarzyna Jasiuk",
    phone: "723 535 393",
    site: "https://katarzynajasiuk.pl/",
    email: "k.jasiuk.radcaprawny@gmail.com",
  },
  {
    name: "Civilis Kancelaria Prawnicza Radca Prawny Zbigniew Baszanowski",
    phone: "(91) 487 27 32",
    site: null,
    email: "n.baszanowskamajcher@baszanowski.eu",
  },
  {
    name: "Kancelaria Radcy Prawnego Natalia Baszanowska-Majcher",
    phone: "(91) 487 27 32",
    site: null,
    email: "n.baszanowskamajcher@baszanowski.eu",
  },
  {
    name: "Izabela Nietupska Kancelaria Radcy Prawnego",
    phone: "(58) 684 97 10",
    site: "https://www.radcanietupska.pl/",
    email: "kancelaria@radcanietupska.pl",
  },
  {
    name: "Rafał Maciesza Kancelaria Radcy Prawnego",
    phone: "603 334 222",
    site: "http://www.kancelariamaciesza.pl/",
    email: "rmaciesza@wp.pl",
  },
  {
    name: "Pelc Grzegorz.Kancelaria Radcy Prawnego",
    phone: "533 237 664",
    site: "http://radca-chorzów.pl/",
    email: "kancelaria@radca-chorzów.pl",
  },
  {
    name: "Zamojska Kancelaria Radcowska Jakub Batalia",
    phone: "793 444 376",
    site: "http://www.kancelaria-batalia.pl/antywindykacja",
    email: "kontakt@kancelaria-batalia.pl",
  },
  {
    name: "DBWP Kancelaria Radców Prawnych Dorf-Burke, Wałga-Pilor Sp.p",
    phone: "(32) 355 87 23",
    site: "http://www.dbwp.pl",
    email: "biuro@dbwp.pl",
  },
  {
    name: "Kancelaria Prawnicza Lesław Obarski Radca Prawny",
    phone: "(18) 443 69 26",
    site: null,
    email: "obarski.kancelaria@wp.pl",
  },
  {
    name: "Wrońska Joanna Kancelaria Radcy Prawnego",
    phone: "602 660 084",
    site: "http://www.radca.opole.pl",
    email: "j.wronska@radca.opole.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Dorota Moros",
    phone: "608 087 934",
    site: "http://www.moros.com.pl",
    email: "moros.prawnik@gmail.com",
  },
  {
    name: "Kancelaria Radcy Prawnego Magdalena Rogalska",
    phone: "602 295 182",
    site: "http://www.radca-rogalska.com.pl/",
    email: "mrogalskakancelaria@gmail.com",
  },
  {
    name: "Anna Weber Kancelaria Radcy Prawnego",
    phone: "695 935 197",
    site: "http://weber-kancelaria.pl",
    email: "weber.kancelaria@gmail.com",
  },
  {
    name: "Delex Kancelaria Radcowsko Rzecznikowska Alina Budner",
    phone: "(42) 637 50 40",
    site: "http://delexkancelaria.com/",
    email: "biuro@delexkancelaria.com",
  },
  {
    name: "Kancelaria Radców Prawnych Gratus s.c.",
    phone: "(58) 550 21 07",
    site: "http://www.gratus.pl",
    email: "kancelaria@gratus.pl",
  },
  {
    name: "Kancelaria radcy prawnego Kamilla Pasiorowska",
    phone: "609 680 162",
    site: null,
    email: "kamila.skibicka@wp.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Marek Stegienta",
    phone: "508 319 435",
    site: "https://kancelariastegienta.pl/",
    email: "mstegienta@kancelariastegienta.pl",
  },
  {
    name: "Małecki Krzysztof Radca Prawny",
    phone: "(52) 397 29 26",
    site: "https://kmkancelaria.pl/",
    email: "biuro@kmkancelaria.pl",
  },
  {
    name: "Joanna Rymarowicz Radca Prawny",
    phone: "570 208 077",
    site: "http://www.joannarymarowicz.pl/",
    email: "radcaprawny@joannarymarowicz.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Piotr Rurak",
    phone: "668 110 224",
    site: null,
    email: "kancelaria.rurak@gmail.com",
  },
  {
    name: "Kancelaria Radcy Prawnego Monika Nietyksza-Faryn",
    phone: "601 823 012",
    site: "http://nietykszafaryn.pl",
    email: "monika.nietykszafaryn14@gmail.com",
  },
  {
    name: "Łukasz Brzozowski Kancelaria Radcy Prawnego",
    phone: "606 652 519",
    site: "https://www.lblegal.pl/",
    email: "biuro@lblegal.pl",
  },
  {
    name: "Lex A’vista Kancelaria Prawnicza Kancelaria Stałego Mediatora Sądowego Przy Sądzie Okręgowym w Szczecinie",
    phone: "691 638 757",
    site: "http://www.lexavista.pl/",
    email: "sergiusz.orlicki@post.pl",
  },
  {
    name: "Wojciech Chojnowski Kancelaria radcy prawnego",
    phone: "601 644 883",
    site: "http://www.kancelariachojnowski.com/",
    email: "chojnowski@kancelariachojnowski.com",
  },
  {
    name: "Wioletta Kalamarz Kancelaria Radcy Prawnego",
    phone: "602 189 171",
    site: "http://wk-kancelaria.com/",
    email: "wkalamarz@wk-kancelaria.com",
  },
  {
    name: "Krzysztof Musiałowski Kancelaria Radcy Prawnego",
    phone: "604 348 827",
    site: "http://www.kancelariamusialowski.pl/",
    email: "kancelaria@musialowski.pl",
  },
  {
    name: "Bizgate-Lex Kancelaria Radcy Prawnego Marek Niewiadomski",
    phone: "501 089 189",
    site: "https://www.bglex.pl/",
    email: "m.niewiadomski@bizgate-lex.pl",
  },
  {
    name: "Patryk Łytko Kancelaria Radcy Prawnego",
    phone: "796 098 741",
    site: "https://www.krp-walbrzych.pl",
    email: "biuro@krp-walbrzych.pl",
  },
  {
    name: "Paczyńska Katarzyna Kancelaria radcy prawnego",
    phone: "(67) 215 31 94",
    site: "http://www.kancelariapaczynska.pl",
    email: "radca@kancelariapaczynska.pl",
  },
  {
    name: "Marcin Deja Kancelaria Radcy Prawnego",
    phone: "603 760 022",
    site: "http://www.radcadeja.pl",
    email: "biuro@radcadeja.pl",
  },
  {
    name: "Rabenda-Ozimek Agnieszka. Kancelaria radcy prawnego",
    phone: "501 015 613",
    site: "http://www.kancelaria-ro.pl",
    email: "agnieszka@kancelaria-ro.pl",
  },
  {
    name: "Piotr Szczucki Kancelaria Radcy Prawnego",
    phone: "697 466 002",
    site: "http://piotr-szczucki-kancelaria-radcy-prawnego.business.site",
    email: "radca@odszkodowania-wypadkowe.com.pl",
  },
  {
    name: "Robert Ślugajski Kancelaria Radcy Prawnego Radca Prawny",
    phone: "600 826 450",
    site: "http://www.kancelaria-slugajski.pl",
    email: "robert@kancelaria-slugajski.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Piotr Belka",
    phone: "607 606 147",
    site: "http://belka-piotr-kancelaria-radcy-prawnego.radcy-prawni.znanyprawnik.pl",
    email: "radca@piotrbelka.pl",
  },
  {
    name: "Magnus Jarosław Krzan",
    phone: "603 654 485",
    site: "https://www.krzanradcaprawny.pl/",
    email: "ssg@kki.pl",
  },
  {
    name: "Bąbol, Bzowski, Klimek Sp.p. Kancelaria Radców Prawnych i Adwokatów",
    phone: "(44) 685 22 55",
    site: "http://bbk-radcowie.pl/",
    email: "sekretariat@bbk-radcowie.pl",
  },
  {
    name: "Magdalena Kulik Kancelaria Radcy Prawnego",
    phone: "505 776 798",
    site: "http://www.kancelariakulik.com",
    email: "kancelaria.kulik@wp.pl",
  },
  {
    name: "Radcy Prawni Poczęty i Wspólnicy Sp.k.",
    phone: "(75) 643 80 50",
    site: "https://www.kancelariajeleniagora.pl/",
    email: "kancelaria@radcyprawni.jgora.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Jarosław Hernik",
    phone: "882 834 999",
    site: "http://www.hernikikolakowski.pl",
    email: "prawo@hernikikolakowski.pl",
  },
  {
    name: "Tomasz Doleżych Kancelaria Radcy Prawnego",
    phone: "505 730 268",
    site: "http://www.radcadolezych.pl",
    email: "kancelaria.dolezych@gmail.com",
  },
  {
    name: "Kancelaria Radcy Prawnego Magdalena Rząp",
    phone: "501 715 393",
    site: "http://www.radcaprawny-dzialdowo.pl/",
    email: "kancelariarzap@gmail.com",
  },
  {
    name: "Katarzyna Grandus Kancelaria Radcy Prawnego",
    phone: "733 130 581",
    site: "http://grandus.com.pl/",
    email: "grandus@onet.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Tomasz Korski",
    phone: "506 739 423",
    site: "https://korski.pl/",
    email: "radca@korski.pl",
  },
  {
    name: "Ewa Mukułowska Kancelaria Radcy Prawnego",
    phone: "601 795 725",
    site: "http://radcaprawnykoszalin.com/",
    email: "ewa.mukulowska@interia.pl",
  },
  {
    name: "Ewelina Wojciechowska Kancelaria Radcy Prawnego",
    phone: "508 480 530",
    site: "http://www.kancelariawojciechowska.pl",
    email: "biuro@kancelariawojciechowska.pl",
  },
  {
    name: "Kancelaria Radców Prawnych M. Mazur R. Kościelska - Mazur s.c.",
    phone: "(81) 740 43 83",
    site: "http://www.mk-radca.pl/",
    email: "kancelaria@mk-radca.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Dominika Kąkol-Papierowska",
    phone: "600 422 761",
    site: "http://radcadarlowo.pl",
    email: "dominika.kakol@gmail.com",
  },
  {
    name: "Jarosław Kamiński Kancelaria Adwokacka",
    phone: "609 652 649",
    site: "https://kancelariakaminski.com.pl/",
    email: "jaroslaw.kaminski@kancelariakaminski.com.pl",
  },
  {
    name: "Kancelaria Radców Prawnych - Anna Szumowska-Juziuk, Sławomir Kuźmiński, Adam Gadomski",
    phone: "603 296 203",
    site: "http://radcaprawny-ostroleka.com.pl",
    email: "juziuk@mp.pl",
  },
  {
    name: "Kancelaria Radców Prawnych Molska-Jerin&Wspólnicy s.c.",
    phone: "662 033 644",
    site: "http://kancelariamj.pl/",
    email: "sekretariat@kancelariamj.pl",
  },
  {
    name: "Izabela Kosińska Kancelaria radcy prawnego",
    phone: "660 133 887",
    site: "http://www.kancelariakosinscy.pl",
    email: "izabela@kancelariakosinscy.pl",
  },
  {
    name: "Dariusz Bączek Kancelaria Radcy Prawnego",
    phone: "(89) 676 56 06",
    site: "http://kancelaria-db.pl/",
    email: "darekbaczek@poczta.fm",
  },
  {
    name: "Temida Kancelaria Adwokacka Adwokat Łukasz Kurek",
    phone: "691 552 477",
    site: "http://www.radcaprawny-grudziadz.pl",
    email: "biuro@radcaprawny-grudziadz.pl",
  },
  {
    name: "Kancelaria adwokacka Adwokat Joanna Kołata-Olczyk",
    phone: "606 589 299",
    site: "http://www.adwokat-lubin.com/",
    email: "joanna.olczyk.pl@gmail.com",
  },
  {
    name: "Kancelaria Prawno - Podatkowa Doradca Podatkowy i Radca Prawny Maciej Mazański",
    phone: "606 832 132",
    site: "http://www.maciejmazanski.pl",
    email: "kancelariamm@op.pl",
  },
  {
    name: "Kancelaria Adwokatów i Radców Prawnych Witkowski, Cabała-Partnerzy Sp.p.",
    phone: "(61) 855 06 91",
    site: "https://witkowski-partnerzy.pl/",
    email: "office@witkowski-partnerzy.pl",
  },
  {
    name: "Marcin Bluszcz Kancelaria adwokacka",
    phone: "608 482 276",
    site: "http://www.pbadwokaci.pl",
    email: "adwokatbluszcz@gmail.com",
  },
  {
    name: "Kuta Maciej Kancelaria Adwokacka",
    phone: "602 189 376",
    site: "https://adwokat-bialapodlaska.pl/",
    email: "maciej.kuta@interia.pl",
  },
  {
    name: "Siergiej i Partnerzy radcy prawni",
    phone: "(89) 527 33 66",
    site: "http://kancelaria-lsp.pl/",
    email: "kancelaria@kancelaria-lsp.pl",
  },
  {
    name: "Vertus s.a. Konsorcjum Prawno Finansowe",
    phone: "(32) 352 01 01",
    site: "http://www.kpfvertus.pl/",
    email: "kancelaria@kpfvertus.pl",
  },
  {
    name: "Bożena Gutt-Mostowy Kancelaria radcy prawnego",
    phone: "(18) 443 69 26",
    site: "https://radcaprawny-guttmostowy.pl/",
    email: "bozenaguttmostowy@gmail.com",
  },
  {
    name: "Rabenda-Ozimek Agnieszka. Kancelaria radcy prawnego",
    phone: "501 015 613",
    site: "http://www.kancelaria-ro.pl",
    email: "agnieszka@kancelaria-ro.pl",
  },
  {
    name: "Rabenda-Ozimek Agnieszka. Kancelaria radcy prawnego",
    phone: "501 015 613",
    site: "http://www.kancelaria-ro.pl",
    email: "agnieszka@kancelaria-ro.pl",
  },
  {
    name: "Rabenda-Ozimek Agnieszka. Kancelaria radcy prawnego",
    phone: "501 015 613",
    site: "http://www.kancelaria-ro.pl",
    email: "agnieszka@kancelaria-ro.pl",
  },
  {
    name: "Magdalena Adamczewska Kancelaria Radcy Prawnego Prawo Leśne, Prawo Łowieckie",
    phone: "605 062 001",
    site: "http://www.adamczewska.com.pl/",
    email: "kancelaria@adamczewska.com.pl",
  },
  {
    name: "Andrzej Czerniec Adwokat Kancelaria Adwokacka",
    phone: "661 070 474",
    site: null,
    email: "adwokat@czerniec.info",
  },
  {
    name: "Kancelaria Adwokacka Adwokat Marcin Wróbel",
    phone: "(55) 642 19 19",
    site: "http://adwokaci-elblag.pl/",
    email: "m.wrobel@adwokaci-elblag.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Karolina Grześkowiak-Szten",
    phone: "691 928 204",
    site: "https://kancelariaszten.pl/",
    email: "grzeskowiak-szten@kancelariaszten.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Karolina Grześkowiak-Szten",
    phone: "691 928 204",
    site: "https://kancelariaszten.pl/",
    email: "grzeskowiak-szten@kancelariaszten.pl",
  },
  {
    name: "Kancelaria Prawna Pretor Sp. z o.o.",
    phone: "(43) 843 08 51",
    site: "http://pretor.net.pl",
    email: "biuro@pretor.net.pl",
  },
  {
    name: "Rafał Maciesza Kancelaria Radcy Prawnego",
    phone: "603 334 222",
    site: "http://www.kancelariamaciesza.pl/",
    email: "rmaciesza@wp.pl",
  },
  {
    name: "Miklas-Kancelaria Prawna Jędrzej Miklas",
    phone: "697 086 806",
    site: "https://kancelaria-miklas.pl/",
    email: "biuro@kancelaria-miklas.pl",
  },
  {
    name: "Monika Adamska Kancelaria Radcy Prawnego",
    phone: "696 412 771",
    site: "https://www.kancelariaprawnakatowice.com/przedmiot.html",
    email: "madamska1@interia.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Lexus Beata Przesmycka-Pawlak",
    phone: "605 408 553",
    site: null,
    email: "bealexus@poczta.onet.pl",
  },
  {
    name: "Adwokacka Kancelaria Adwokat Natasza Jemielity Adwokat Magdalena Gudzowska",
    phone: "605 582 434",
    site: "http://www.adwokatgorzowski.pl",
    email: "natasza.jemielity@adwokatura.pl",
  },
  {
    name: "Andrzej Tysier Kancelaria podatkowa",
    phone: "602 186 276",
    site: "http://www.tgdkancelarie.pl",
    email: "atysier@gmail.com",
  },
  {
    name: "Alfa Kancelaria Radcy Prawnego Adrian Adamski",
    phone: "502 245 545",
    site: "http://www.alfa-silesia.pl",
    email: "kancelaria@alfa-silesia.pl",
  },
  {
    name: "Dębska-Gadzała Iwona Kancelaria Radcy Prawnego",
    phone: "609 607 715",
    site: null,
    email: "kancelariagadzala@wp.pl",
  },
  {
    name: "Ewa Panowicz Kancelaria Radcy Prawnego",
    phone: "509 275 216",
    site: "http://www.radcaprawnyleszno.pl",
    email: "e.panowicz@radcaprawnyleszno.pl",
  },
  {
    name: "Aldona Marciniak Kancelaria Radcy Prawnego",
    phone: "(56) 643 16 05",
    site: null,
    email: "kancelaria_chelminska@op.pl",
  },
  {
    name: "Anna Dawid-Krajewska Radca prawny Kancelaria prawna",
    phone: "502 907 088",
    site: "http://radcaprawnyostroleka.pl/",
    email: "prawnik.ostroleka@gmail.com",
  },
  {
    name: "Anna Dawid-Krajewska Radca Prawny Kancelaria Prawna",
    phone: "502 907 088",
    site: "http://radcaprawnyostroleka.pl/",
    email: "prawnik.ostroleka@gmail.com",
  },
  {
    name: "Kancelaria Radcy Prawnego Maciej Bakalarz",
    phone: "601 433 966",
    site: "https://www.bakalarz.eu/",
    email: "radca@bakalarz.eu",
  },
  {
    name: "Kancelaria Radcy Prawnego Radosław Micewicz-Kłoda",
    phone: "(58) 553 05 21",
    site: "http://micewicz-kloda.pl/",
    email: "kancelaria@micewicz-kloda.pl",
  },
  {
    name: "Radca Prawny Dariusz Wojtak Kancelaria Radcy Prawnego",
    phone: "797 314 602",
    site: "http://kancelariazamosc.pl",
    email: "kancelaria.wojtak@wp.pl",
  },
  {
    name: "Kostecki I Partnerzy Kancelaria Radców Prawnych Sp.Partnerska",
    phone: "(65) 520 22 12",
    site: "http://www.kancelaria-kostecki.pl/",
    email: "kancelaria@kancelaria-kostecki.pl",
  },
  {
    name: "Radca Prawny Garus Łukasz",
    phone: "608 073 094",
    site: "https://www.radcaprawnygarus.pl/",
    email: "lukgar@wp.pl",
  },
  {
    name: "Kancelaria Prawna Radca Prawny Jolanta Skuratowicz",
    phone: "602 672 727",
    site: null,
    email: "jolantaskuratowicz1@onet.pl",
  },
  {
    name: "Kancelarie Prawne Zach & Partyńska Duchnik",
    phone: "607 160 112",
    site: "http://www.kancelariazpd.pl",
    email: "biuro@kancelariazpd.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Agnieszka Cieślińska",
    phone: "508 132 367",
    site: null,
    email: "krp_cieslinska@wp.pl",
  },
  {
    name: "Kancelaria Radcy Prawnego Michał Rusinek",
    phone: "609 747 197",
    site: "https://kancelaria-rusinek.pl/",
    email: "rusinek@kancelaria-rusinek.pl",
  },
];

export default radcyprawni;
