const salonykosmetyczne = [
  {
    name: "Salon kosmetyczny, gabinet kosmetologii i medycyny estetycznej, tlenoterapia hiperbaryczna komora tlenowa Madness Estetic",
    phone: "535 166 554",
    site: null,
    email: "madnessestetic@onet.eu",
  },
  {
    name: "Katleja Day SPA Anita Szlachetka",
    phone: "606 876 166",
    site: "http://www.katlejadayspa.pl",
    email: "gabinet@katlejadayspa.pl",
  },
  {
    name: "Divia Marta Mendel",
    phone: "601 550 407",
    site: "https://divia.pl/",
    email: "marta.mendel@divia.pl",
  },
  {
    name: "Instytut Urody Diamond Beauty",
    phone: "514 627 619",
    site: "http://www.diamondbeauty.pl",
    email: "eveee86@gmail.com",
  },
  {
    name: "Casolla Katarzyna Buczkowska",
    phone: "516 301 308",
    site: "https://casolla.pl/",
    email: "casolla.gabinet@gmail.com",
  },
  {
    name: "Amarone Studio urody",
    phone: "883 474 783",
    site: "https://www.gabinetkosmetyczny.lodz.pl/",
    email: "amarone@gabinetkosmetyczny.lodz.pl",
  },
  {
    name: 'Centrum Urody "Estetica"',
    phone: "(48) 363 27 31",
    site: "http://www.estetica.radom.pl/",
    email: "estetica.radom@gmail.com",
  },
  {
    name: "Ms Smile Stomatologia I Medycyna Estetyczna",
    phone: "530 008 406",
    site: "https://mssmile.pl/",
    email: "biuro@mssmile.pl",
  },
  {
    name: "Ona Odnova Kosmetologia i Medycyna Esteryczna",
    phone: "666 000 559",
    site: "https://booksy.com/pl-pl/65638_ona-odnova_salon-kosmetyczny_20383_gdansk",
    email: "onaodnova@gmail.com",
  },
  {
    name: "Beata Petrova kosmetologia i fizjoterapia",
    phone: "(22) 663 39 98",
    site: "https://www.petrova.pl/",
    email: "gabinet@petrova.pl",
  },
  {
    name: "Studio Wizażu i Kosmetyki Motyl Sylwia Zalińska",
    phone: "882 096 347",
    site: "https://www.makijazslupsk.pl/",
    email: "studiomotyl@wp.pl",
  },
  {
    name: "Babski Świat",
    phone: "537 092 053",
    site: null,
    email: "pawmielczarek285@gmail.com",
  },
  {
    name: "Lab2 Sp. z o.o.",
    phone: "733 541 959",
    site: null,
    email: "lab2studia@gmail.com",
  },
  {
    name: "Anna Salon Fryzjerski Anna Woszczyńska",
    phone: "577 140 802",
    site: null,
    email: "salonfryzjerskios.borek@gmail.com",
  },
  {
    name: "Ostromecka Aleksandra- Salon Urody Euphoria",
    phone: "512 365 330",
    site: "http://www.poczujeuforie.pl",
    email: "m.ostromecki@intur.pl",
  },
  {
    name: "Image Studio Urody Małgorzata Nowosad",
    phone: "(81) 825 95 29",
    site: null,
    email: "malgorzata.nowosad@gmail.com",
  },
  {
    name: "Laser Studio 4-Profesjonalna Depilacja Laserowa",
    phone: "(56) 660 20 00",
    site: "http://laserstudio4.pl/",
    email: "info@laserstudio4.pl",
  },
  {
    name: "Estetic Małgorzata Olejnik",
    phone: "694 391 927",
    site: "https://esteticrzeszow.pl/",
    email: "amla202@o2.pl",
  },
  {
    name: "Centrum Usługowo-Szkoleniowe Violin Wioleta Podolska",
    phone: "601 067 885",
    site: "http://perfectlashes-academy.pl",
    email: "wioleta.podolska@op.pl",
  },
  {
    name: "Salon Urody Orchidea Justyna Jańczuk",
    phone: "666 829 687",
    site: null,
    email: "justyna-janczuk@wp.pl",
  },
  {
    name: "Paulina Kwaśniewska Firma Usługa Rzęsomania",
    phone: "663 511 776",
    site: null,
    email: "paulinakwasniewskaaa@gmail.com",
  },
  {
    name: "Lio Crystal-Instytut Estetyki Ciała Barbara Koś",
    phone: "691 103 900",
    site: "http://www.lio-instytut.pl",
    email: "recepcja@Lio-instytut.pl",
  },
  {
    name: "Joanna Jamroz Salon kosmetyczny",
    phone: "604 838 196",
    site: "http://www.gabinetkosmetyczny-swiebodzin.pl",
    email: "jjoanna12@onet.pl",
  },
  {
    name: "Salon Stylizacji Joanna Tadewicz",
    phone: "661 371 122",
    site: null,
    email: "j.tadewicz@gmail.com",
  },
  {
    name: "Beautyway Karolina Gierszewska",
    phone: "791 834 934",
    site: "https://gabinet-kosmetyczny-beautyway.business.site/",
    email: "salon.beautyway@gmail.com",
  },
  {
    name: "Magda Kozak Babskie Fanaberie",
    phone: "661 863 337",
    site: null,
    email: "babskiefanaberieumagdykozak@gmail.com",
  },
  {
    name: "Malinowe Studio Urody Milena Malinowska",
    phone: "517 963 597",
    site: "http://malinowe-studio-urody-milena-malinowska.business.site",
    email: "milenamalinowska5@gmail.com",
  },
  {
    name: "Maja Drozdowska STUDIO",
    phone: "695 564 791",
    site: null,
    email: "majka.drozdowska@o2.pl",
  },
  {
    name: "Salon kosmetyczny mega Agnieszka Chomicka",
    phone: "516 575 620",
    site: null,
    email: "s.chom@wp.pl",
  },
  {
    name: "Beauty of Essence - makijaż permanentny, stylizacja rzęs i paznokci.",
    phone: "517 696 087",
    site: null,
    email: "katarzyna.sendrowicz@gmail.com",
  },
  {
    name: "Lashes Home Gabinet Stylizacji Rzęs Anna Bąk",
    phone: "793 306 070",
    site: null,
    email: "ania_n05@wp.pl",
  },
  {
    name: "BEAUTY SPA Iwona Olszowiak",
    phone: "662 070 569",
    site: null,
    email: "iwona.olszowiak@wp.pl",
  },
  {
    name: "Beauty Glam Karolina Bartusiak",
    phone: "514 409 046",
    site: "https://beauty-glam-stylizacja-rzes-szczecin-karolina.business.site/",
    email: "karolina-bartusiak@o2.pl",
  },
  {
    name: "Edelin Edyta Kwiecińska",
    phone: "601 093 668",
    site: null,
    email: "edyta.kwiecinska17@wp.pl",
  },
  {
    name: "Ewelina Kurowska Pracownia Kosmetyczna Eve",
    phone: "789 014 714",
    site: null,
    email: "pracowniakosmetycznaeve@gmail.com",
  },
  {
    name: "Beauty By Marta Nasiadek",
    phone: "663 446 445",
    site: null,
    email: "marta_nn6@wp.pl",
  },
  {
    name: "Beauty Centrum Paulina Wypych",
    phone: "516 139 569",
    site: "https://www.beauty-centrum.pl/",
    email: "paulina.wypych92@gmail.com",
  },
  {
    name: "Stylizacja Paznokci Sonia Czarnecka",
    phone: "516 195 989",
    site: "http://www.facebook.com/pages/category/Skin-Care-Service/Sonia-Czarnecka-Nails-Instruktor-Eclair-1772197329709167/",
    email: "soncza4314@gmail.com",
  },
  {
    name: "Wilczyńska Magdalena Salon Odnowy Biologicznej",
    phone: "782 115 012",
    site: null,
    email: "magda_wilczynska@tlen.pl",
  },
  {
    name: "Ewelina Radoń Klinika Urody i Laseroterapii Ivilin",
    phone: "506 591 316",
    site: "http://ivilin.pl/",
    email: "biuroivilin@gmail.com",
  },
  {
    name: "Ergoline Kinga Śrubarczyk",
    phone: "511 193 378",
    site: "http://solarium.business.site",
    email: "kinga.srubarczyk@gmail.com",
  },
  {
    name: "Beauty Secret Justyna Szumska",
    phone: "(22) 672 83 34",
    site: "http://www.beautysecret.pl",
    email: "salon@beautysecret.pl",
  },
  {
    name: "Laser 4 Studio-Profesjonalna Depilacja Laserowa",
    phone: "(56) 646 16 12",
    site: "http://laserstudio4.pl/",
    email: "info@laserstudio4.pl",
  },
  {
    name: "Laser Studio 4-Profesjonalna Depilacja Laserowa",
    phone: "(52) 582 73 12",
    site: "http://laserstudio4.pl/",
    email: "info@laserstudio4.pl",
  },
  {
    name: "Studio Stylu i Urody s.c. Danuta Reizer, Monika Reizer",
    phone: "(12) 281 36 61",
    site: null,
    email: "monika1647@poczta.onet.pl",
  },
  {
    name: "Studio Figura Beata Hetman",
    phone: "577 533 060",
    site: "https://mikolow.studio-figura.pl/",
    email: "sfmikolow@wp.pl",
  },
  {
    name: "Instytut Zdrowia i Urody Barbara Miranowska",
    phone: "733 982 982",
    site: "https://elblag.yasumi.pl/",
    email: "elblag@yasumi.pl",
  },
  {
    name: "Salon urody Scarlett",
    phone: "698 642 698",
    site: null,
    email: null,
  },
  {
    name: "Wiecznie Młodzi Strefa Beauty",
    phone: "577 403 711",
    site: "https://www.wiecznie-mlodzi.pl/",
    email: "kontakt@wiecznie-mlodzi.pl",
  },
  {
    name: "Centrum Profilaktyki Zdrowia i Biorezonansu Helena Klucz",
    phone: "600 340 869",
    site: null,
    email: "halina.tiens@gmail.com",
  },
  {
    name: "M&M Beauty Maria Malczewska",
    phone: "512 663 601",
    site: null,
    email: "mary.93@wp.pl",
  },
  {
    name: "Julia Gabinet Kosmetyczny Ewa Faber",
    phone: "508 363 261",
    site: "http://www.kosmetykajulia.pl/",
    email: "faber.ewa57@gmail.com",
  },
  {
    name: "Magia Urody Malwina Majchrzak-Dominiak",
    phone: "725 201 875",
    site: "https://akademiamagiaurody.pl/",
    email: "majchrzak.szkolenia@gmail.com",
  },
  {
    name: "Nailashes Grażyna Klub-Jas",
    phone: "515 140 965",
    site: null,
    email: "nailashes.studiourody@gmail.com",
  },
  {
    name: "Novaderm Gabinet Kosmetologii i Podologii Martyna Tompolska",
    phone: "883 141 615",
    site: null,
    email: "novaderm@op.pl",
  },
  {
    name: "Beauty Room Ewelina Sądel",
    phone: "508 758 118",
    site: null,
    email: "ewelinasadel@wp.pl",
  },
  {
    name: "Klinika Urody I Podologii Miu Miu mgr Barbara Kliś",
    phone: "519 154 888",
    site: null,
    email: "klinikamiumiu@gmail.com",
  },
  {
    name: "Gabinet kosmetyczny Efekt Motyla Magdalena Wójcik Odmładzanie skóry, usuwanie zmarszczek i ujędrnianie ciała",
    phone: "663 584 075",
    site: "https://www.salonefektmotyla.pl/",
    email: "madzia.wojcik.86@wp.pl",
  },
  {
    name: "Hair Beauty Kateryna Vyrobek",
    phone: "690 072 662",
    site: null,
    email: "olena.vurobek@gmail.com",
  },
  {
    name: "Be Glam stylizacja paznokci, rzęs i brwi Elwira Listwan",
    phone: "504 968 087",
    site: "http://www.beglamef.pl",
    email: "listwanelwira@gmail.com",
  },
  {
    name: "Pmu Beauty Room Katarzyna Kamińska",
    phone: "729 320 219",
    site: null,
    email: "pmubeautyroom@gmail.com",
  },
  {
    name: "Atena Centrum Zdrowia I Urody Barbara Myśliwy",
    phone: "602 625 108",
    site: "http://www.atenacentrum.pl",
    email: "atena@nysa.com.pl",
  },
  {
    name: "Gabinet Podologiczny Ulga Stopom Gabriela Brudny",
    phone: "733 331 155",
    site: "http://www.podologbielsko.com/",
    email: "gababielsko@autograf.pl",
  },
  {
    name: "Salon Kosmetyczny Katarzyna Pańta",
    phone: "609 766 739",
    site: null,
    email: "katarzyna.panta@wp.pl",
  },
  {
    name: "Salon Urody Magda Cedzidło Magdalena",
    phone: "606 821 366",
    site: "http://salonurodymagda.pl/",
    email: "info@salonurodymagda.pl",
  },
  {
    name: "Beauty Studio - Gabinet Kosmetyczny Agnieszka Bandrowska",
    phone: "883 585 666",
    site: null,
    email: "abandrowska@hotmail.com",
  },
  {
    name: "Las Joga Katarzyna Borowska",
    phone: "608 689 500",
    site: "https://lasjoga.pl/",
    email: "lassjoga@gmail.com",
  },
  {
    name: "Maja Banachowicz MBelle",
    phone: "514 006 179",
    site: null,
    email: "anwerse@wp.pl",
  },
  {
    name: "Nobu kosmetologia estetyczna",
    phone: "798 012 811",
    site: "https://nobu.com.pl/",
    email: "nobuspa.bialystok@gmail.com",
  },
  {
    name: "Katleja Day SPA Anita Szlachetka",
    phone: "606 876 166",
    site: "http://www.katlejadayspa.pl",
    email: "gabinet@katlejadayspa.pl",
  },
  {
    name: "Gabinet Kosmetologiczny Kosmotalia Natalia Ciołko",
    phone: "572 651 394",
    site: null,
    email: "gab.kosmotalia@gmail.com",
  },
  {
    name: "Wariacje Piękna Sylwia Piwowarczyk",
    phone: "537 611 861",
    site: "https://wariacjepiekna.pl/",
    email: "lavenida@wp.pl",
  },
  {
    name: "Gabinet Kosmetyczny Sekret Małgorzata Garstka",
    phone: "604 632 214",
    site: "http://kosmetyczkatarnow.eu",
    email: "gosia.garstka@op.pl",
  },
  { name: "Ewelina Pająk", phone: "782 002 016", site: null, email: null },
  {
    name: "Pracownia Urody Prosta Kreska - Makijaż Permanentny, Zabiegi, Medycyna Estetyczna",
    phone: "537 334 111",
    site: null,
    email: "gabinetprostakreska@gmail.com",
  },
  {
    name: "Marzenie Gabinet Kosmetyczno-Fryzjerski Marzena Jamuła",
    phone: "515 137 004",
    site: null,
    email: "marzena_jamula@o2.pl",
  },
  {
    name: "Picaflor - Pracownia Urody Stylizacja Paznokci Patrycja Jankowska",
    phone: "609 947 117",
    site: null,
    email: "patrycjajankowska06@gmail.com",
  },
  {
    name: "Dafne Gabinet Kosmetyczny",
    phone: "(67) 215 45 49",
    site: null,
    email: "agnieszkasosnowskadafne@o2.pl",
  },
  {
    name: "Kamila Gabinet Podologiczno-Kosmetyczny Mariola Wawełczyk",
    phone: "500 063 524",
    site: "http://www.gabinetkamila.pl",
    email: "gabinetkamila@onet.pl",
  },
  {
    name: "Prestiż Agnieszka Pławiak",
    phone: "784 507 991",
    site: null,
    email: "agnieszka.plawiak@opoczta.pl",
  },
  {
    name: "An-Tre Aneta Trescher Salon Kosmetyczny",
    phone: "662 632 788",
    site: null,
    email: "atusia4@tlen.pl",
  },
  {
    name: "Krzysztof Szubert Agencja Marketingowa",
    phone: "(61) 670 60 81",
    site: "https://www.kosmetyka-podologia.pl/",
    email: "gabinet@kosmetyka-podologia.pl",
  },
  {
    name: "Studio Mb Marlena Błażejczyk Fryzjerstwo Kosmetyka Stylizacja Paznokci",
    phone: "797 233 250",
    site: null,
    email: "studiomb@interia.pl",
  },
  {
    name: "Moniq Monika Parzątka-Lipińska",
    phone: "572 568 318",
    site: null,
    email: "lip_mon@wp.pl",
  },
  {
    name: "Estetica Eko Spa Izabela Gil",
    phone: "(23) 654 91 30",
    site: "http://www.studioiza.pl",
    email: "izabela.gil@studioiza.pl",
  },
  {
    name: "Avangarda Studio Ewelina Korycińska",
    phone: "515 654 085",
    site: null,
    email: "e.m.korycinska@gmail.com",
  },
  {
    name: "Studio urody beauty Zuzanna Pudlik",
    phone: "535 308 308",
    site: null,
    email: "zpudlik@vp.pl",
  },
  {
    name: "Monika Gross Si Bella SPA",
    phone: "(22) 400 00 10",
    site: "http://www.sibella.pl",
    email: "kontakt@sibella.pll",
  },
  {
    name: "MAGNOLIA - Studio Kosmetyczne i Masażu",
    phone: "531 969 890",
    site: "https://www.masaz-strzegom.pl/",
    email: "dorota.sas@op.pl",
  },
  {
    name: "Paulina Siudeja Studio Urody La Mia",
    phone: "721 554 452",
    site: "https://studio-urody-la-mia.business.site/",
    email: "siudka2007@gmail.com",
  },
  {
    name: "Gabinet Kosmetyczny ZEA",
    phone: "519 840 207",
    site: null,
    email: "gabinet.zea@gmail.com",
  },
  {
    name: "M K Beauty",
    phone: "733 779 758",
    site: null,
    email: "mariiadakhnova@gmail.com",
  },
  {
    name: "Marta Klimkowicz mgr kosmetologii Centrum Kosmetologiczne",
    phone: "668 301 544",
    site: "http://centrumkosmetologiczne-mk.pl",
    email: "martaklimkowicz@gmail.com",
  },
  {
    name: "Studio Urody Milena Szczepańska",
    phone: "507 785 536",
    site: null,
    email: "milenaa44102@gmail.com",
  },
  {
    name: "Stylizacja Paznokci Maluj i baluj Zuzanna Lewandowska",
    phone: "536 974 166",
    site: null,
    email: "zlewandowska@icloud.com",
  },
  {
    name: "Sugar Sfera",
    phone: "664 344 641",
    site: null,
    email: "kristina.m0785@gmail.com",
  },
  {
    name: "Agnieszka Wrześniewska-Stylizacja rzęs&makijaż permanentny",
    phone: "516 472 115",
    site: "http://www.facebook.com/studiowrzesniewska/",
    email: "agnieszka.wrzesniewska@poczta.onet.pl",
  },
  {
    name: "BELLA Makijaż Permanentny i Kosmetologia JOANNA RATAJCZYK",
    phone: "694 652 700",
    site: "https://www.bellaslupsk.com/",
    email: "bellaslupsk@wp.pl",
  },
  {
    name: "Glamour Paulina Krzykowska-Kalinowska",
    phone: "506 206 009",
    site: "https://www.gabinetglamour.pl/",
    email: "gabinetglamour@gmail.com",
  },
  {
    name: "Usługi Kosmetyczne Katarzyna Kurzydlak",
    phone: "731 300 190",
    site: "https://katarzyna-kurzydlak-uslugi-kosmetyczne.business.site/",
    email: "radetzky369@gmail.com",
  },
  {
    name: "Frisor Karolina Kwidzińska",
    phone: "664 474 033",
    site: "http://studio-fryzjerskie-frisor.business.site",
    email: "karolinagalik1@wp.pl",
  },
  {
    name: "Pure Beauty Adrianna Chudzicka",
    phone: "726 479 144",
    site: null,
    email: "pureadrianna@gmail.com",
  },
  {
    name: "Beata Misińska z Pazurem",
    phone: "792 899 621",
    site: null,
    email: "bietka.kubicka@wp.pl",
  },
  {
    name: "Gracja Nails - Stylizacja paznokci",
    phone: "509 439 726",
    site: null,
    email: "joannastrzelczyk0@wp.pl",
  },
  {
    name: "Kinga Bednarek Make Up And Beauty Makijaż okolicznościowy, opalanie natryskowe",
    phone: "695 853 053",
    site: null,
    email: "bednarekkinga99@gmail.com",
  },
  {
    name: "E.S. Makijaż Permanentny i Opalanie Natryskowe Tanexpert-Usługi Mobilne Ewa Sasak",
    phone: "508 412 421",
    site: null,
    email: "ewa.sasak77@gmail.com",
  },
  {
    name: "Salon Kosmetyczny Beauty Bar",
    phone: "723 086 975",
    site: null,
    email: "dominika.luczynskaa@gmail.com",
  },
  {
    name: "Salon urody Anna Zielińska",
    phone: "730 020 985",
    site: "https://www.azsalonurody.pl/",
    email: "salonurodyaz@gmail.com",
  },
  {
    name: "Sekret Piękna Natalia Sobczak",
    phone: "789 181 280",
    site: "https://www.kosmetyka-lodz.pl/",
    email: "sekretpieknakosmetyka@gmail.com",
  },
  {
    name: "Stylizacja rzęs - Perfect Lashes By Daria Świątczak",
    phone: "535 367 793",
    site: "http://www.perfectlashesbydaria.pl",
    email: "daria.swiatczak@vp.pl",
  },
  {
    name: "Alga Salon kosmetyczny",
    phone: "(22) 549 90 33",
    site: "http://alga.waw.pl/",
    email: "salonalga@wp.pl",
  },
  {
    name: "Studio Kosmetyczne Róża Siejak",
    phone: "606 375 649",
    site: "http://www.kosmetykapoznan.eu",
    email: "gabinet@kosmetykapoznan.pl",
  },
  {
    name: "Oksana Novitska Gabinet Kosmetyczny",
    phone: "690 062 870",
    site: "https://oksana-novitska-gabinet-kosmetyczny.business.site/",
    email: "nowickaksu@gmail.com",
  },
  {
    name: "Studio Urody Discolor",
    phone: "500 067 781",
    site: null,
    email: "okotarska1@gmail.com",
  },
  {
    name: "Akademia Urody Iga Płotka-Stańczak",
    phone: "505 022 837",
    site: null,
    email: "iga-1986@o2.pl",
  },
  {
    name: "Beauty Bar Małgorzata Rutkowska - stylizacja rzęs, henna pudrowa, makijaż",
    phone: "602 753 651",
    site: "https://mrbeautybar.pl/",
    email: "beautybarwolin@gmail.com",
  },
  {
    name: "Beauty& MakeUp Magdalena Wach",
    phone: "601 621 814",
    site: null,
    email: "mazur-magdalena@wp.pl",
  },
  {
    name: "Fabulous Lady Salon Kosmetyki Profesjonalnej",
    phone: "792 072 294",
    site: null,
    email: "salonfabulous@gmail.com",
  },
  {
    name: "Hathor Kosmetyka, Zabiegi, Szkolenia",
    phone: "535 100 303",
    site: null,
    email: "mrostapczuk@wp.pl",
  },
  {
    name: "Joanna Sekuła Makeup Beauty",
    phone: "535 889 752",
    site: null,
    email: "joannasekula.makeupbeauty@gmail.com",
  },
  {
    name: "Studio Urody I Depilacji Laserowej Anna Olejniczak",
    phone: "516 175 501",
    site: "https://studiouid.pl/",
    email: "epilacja@studiouid.pl",
  },
  {
    name: "Aleja Piękności Salon kosmetyczny Justyna Gałan",
    phone: "519 168 483",
    site: null,
    email: "justyna.galan@onet.pl",
  },
  {
    name: "Studio Kosmetyczne Adell Klaudia Jadam",
    phone: "535 456 125",
    site: null,
    email: "klaudia.jadam@o2.pl",
  },
  {
    name: "Hybrydowa Pokusa Ewelina Ziemkiewicz",
    phone: "517 127 976",
    site: null,
    email: "ewelina.hybrydowa.pokusa@wp.pl",
  },
  {
    name: "Centrum Estetyki Ciała Dorota Niedziółka Fryzjerstwo i Kosmetyka",
    phone: "661 457 279",
    site: "http://cec.wloclawek.pl/",
    email: "centrumestetyki@gmail.com",
  },
];

export default salonykosmetyczne;
